export const symbols = {
    "clearsky" : "🌞"
  , "clearsky_day" : "🌞"
  , "clearsky_day" : "🌞"
  , "clearsky_night" : "🌜"
  , "cloudy" : "☁️"
  , "cloudy_day" : "☁️"
  , "cloudy_night" : "☁️"
  , "fair" : "🌤️"
  , "fair_day" : "🌤️"
  , "fair_night" : "🌜"
  , "fog" : "🌫️"
  , "fog_day" : "🌫️"
  , "fog_night" : "🌫️"
  , "heavyrain" : "🌧️"
  , "heavyrain_day" : "🌧️"
  , "heavyrain_night" : "🌧️"
  , "heavyrainandthunder" : "🌧️"
  , "heavyrainandthunder_day" : "🌧️"
  , "heavyrainandthunder_night" : "🌧️"
  , "heavyrainshowers" : "🌧️"
  , "heavyrainshowers_day" : "🌧️"
  , "heavyrainshowers_night" : "🌧️"
  , "heavyrainshowersandthunder" : "🌧️"
  , "heavyrainshowersandthunder_day" : "🌧️"
  , "heavyrainshowersandthunder_night" : "🌧️"
  , "heavysleet" : "❄️ "
  , "heavysleet_day" : "❄️ "
  , "heavysleet_night" : "❄️ "
  , "heavysleetandthunder" : "❄️ "
  , "heavysleetandthunder_day" : "❄️ "
  , "heavysleetandthunder_night" : "❄️ "
  , "heavysleetshowers" : "❄️ "
  , "heavysleetshowers_day" : "❄️ "
  , "heavysleetshowers_night" : "❄️ "
  , "heavysleetshowersandthunder" : "❄️ "
  , "heavysleetshowersandthunder_day" : "❄️ "
  , "heavysleetshowersandthunder_night" : "❄️ "
  , "heavysnow" : "❄️ "
  , "heavysnow_day" : "❄️ "
  , "heavysnow_night" : "❄️ "
  , "heavysnowandthunder" : "❄️ "
  , "heavysnowandthunder_day" : "❄️ "
  , "heavysnowandthunder_night" : "❄️ "
  , "heavysnowshowers" : "❄️ "
  , "heavysnowshowers_day" : "❄️ "
  , "heavysnowshowers_night" : "❄️ "
  , "heavysnowshowersandthunder" : "❄️ "
  , "heavysnowshowersandthunder_day" : "❄️ "
  , "heavysnowshowersandthunder_night" : "❄️ "
  , "lightrain" : "🌧️"
  , "lightrain_day" : "🌧️"
  , "lightrain_night" : "🌧️"
  , "lightrainandthunder" : "🌧️"
  , "lightrainandthunder_day" : "🌧️"
  , "lightrainandthunder_night" : "🌧️"
  , "lightrainshowers" : "🌧️"
  , "lightrainshowers_day" : "🌧️"
  , "lightrainshowers_night" : "🌧️"
  , "lightrainshowersandthunder" : "🌧️"
  , "lightrainshowersandthunder_day" : "🌧️"
  , "lightrainshowersandthunder_night" : "🌧️"
  , "lightsleet" : "❄️ "
  , "lightsleet_day" : "❄️ "
  , "lightsleet_night" : "❄️ "
  , "lightsleetandthunder" : "❄️ "
  , "lightsleetandthunder_day" : "❄️ "
  , "lightsleetandthunder_night" : "❄️ "
  , "lightsleetshowers" : "❄️ "
  , "lightsleetshowers_day" : "❄️ "
  , "lightsleetshowers_night" : "❄️ "
  , "lightsnow" : "❄️ "
  , "lightsnow_day" : "❄️ "
  , "lightsnow_night" : "❄️ "
  , "lightsnowandthunder" : "❄️ "
  , "lightsnowandthunder_day" : "❄️ "
  , "lightsnowandthunder_night" : "❄️ "
  , "lightsnowshowers" : "❄️ "
  , "lightsnowshowers_day" : "❄️ "
  , "lightsnowshowers_night" : "❄️ "
  , "lightssleetshowersandthunder" : "❄️ "
  , "lightssleetshowersandthunder_day" : "❄️ "
  , "lightssleetshowersandthunder_night" : "❄️ "
  , "lightssnowshowersandthunder" : "❄️ "
  , "lightssnowshowersandthunder_day" : "❄️ "
  , "lightssnowshowersandthunder_night" : "❄️ "
  , "partlycloudy" : "🌥️"
  , "partlycloudy_day" : "🌥️"
  , "partlycloudy_day" : "🌥️"
  , "partlycloudy_night" : "🌥️"
  , "rain" : "🌜"
  , "rain" : "🌧️"
  , "rain_day" : "🌜"
  , "rain_night" : "🌜"
  , "rainandthunder" : "🌜"
  , "rainandthunder_day" : "🌜"
  , "rainandthunder_night" : "🌜"
  , "rainshowers" : "🌦️"
  , "rainshowers_day" : "🌦️"
  , "rainshowers_night" : "🌦️"
  , "rainshowersandthunder" : "🌦️"
  , "rainshowersandthunder_day" : "🌦️"
  , "rainshowersandthunder_night" : "🌦️"
  , "sleet" : "❄️ "
  , "sleet_day" : "❄️ "
  , "sleet_night" : "❄️ "
  , "sleetandthunder" : "❄️ "
  , "sleetandthunder_day" : "❄️ "
  , "sleetandthunder_night" : "❄️ "
  , "sleetshowers" : "❄️ "
  , "sleetshowers_day" : "❄️ "
  , "sleetshowers_night" : "❄️ "
  , "sleetshowersandthunder" : "❄️ "
  , "sleetshowersandthunder_day" : "❄️ "
  , "sleetshowersandthunder_night" : "❄️ "
  , "snow" : "❄️ "
  , "snow_day" : "❄️ "
  , "snow_night" : "❄️ "
  , "snowandthunder" : "❄️ "
  , "snowandthunder_day" : "❄️ "
  , "snowandthunder_night" : "❄️ "
  , "snowshowers" : "❄️ "
  , "snowshowers_day" : "❄️ "
  , "snowshowers_night" : "❄️ "
  , "snowshowersandthunder" : "❄️ "
  , "snowshowersandthunder_day" : "❄️ "
  , "snowshowersandthunder_night" : "❄️ "
}
